const goetiaDemons = [
  { name: "Bael", rank: "King", legions: 66, appearance: "Man, cat, toad, or all three; hoarse voice", primaryPowers: "Invisibility, wisdom, cunning, favor with rulers" },
  { name: "Agares", rank: "Duke", legions: 31, appearance: "Old man riding crocodile, hawk on fist", primaryPowers: "Causes earthquakes, teaches languages, destroys dignities, makes runaways return" },
  { name: "Vassago", rank: "Prince", legions: 26, appearance: "Mighty being", primaryPowers: "Declares past/future, finds hidden/lost things" },
  { name: "Gamigin", rank: "Marquis", legions: 30, appearance: "Small horse or donkey", primaryPowers: "Teaches liberal sciences, gives accounts of souls who died in sin" },
  { name: "Marbas", rank: "President", legions: 36, appearance: "Lion, then man", primaryPowers: "Reveals secrets, causes/heals diseases, shapeshifting, mechanical arts" },
  { name: "Valefor", rank: "Duke", legions: 10, appearance: "Lion with bellowing head", primaryPowers: "Tempts theft, good familiar but treacherous" },
  { name: "Amon", rank: "Marquis", legions: 40, appearance: "Wolf with serpent tail, vomiting fire; or man with raven head", primaryPowers: "Reconciles friends/foes, reveals past/future" },
  { name: "Barbatos", rank: "Duke", legions: 30, appearance: "With four kings and music", primaryPowers: "Understands animals, reveals treasures, past/future, reconciles friends" },
  { name: "Paimon", rank: "King", legions: 200, appearance: "Effeminate man on camel, loud band", primaryPowers: "Teaches arts/sciences, gives dignities, binds men to will, familiars" },
  { name: "Buer", rank: "President", legions: 50, appearance: "Star form or lion", primaryPowers: "Teaches philosophy/herbs, heals diseases, good familiar" },
  { name: "Gusion", rank: "Duke", legions: 40, appearance: "Unknown (baboon-like in some)", primaryPowers: "Reveals past/present/future, honors, friendship" },
  { name: "Sitri", rank: "Prince", legions: 60, appearance: "Leopard head, griffin wings, then beautiful human", primaryPowers: "Inflames love/lust, reveals secrets of women" },
  { name: "Beleth", rank: "King", legions: 85, appearance: "Terrifying on pale horse with music", primaryPowers: "Causes love (men/women)" },
  { name: "Leraje", rank: "Marquis", legions: 30, appearance: "Archer in green", primaryPowers: "Causes battles, putrefies arrow wounds" },
  { name: "Eligos", rank: "Duke", legions: 60, appearance: "Knight with lance/banner/scepter", primaryPowers: "Reveals hidden things, future wars, favor of lords" },
  { name: "Zepar", rank: "Duke", legions: 26, appearance: "Soldier in red", primaryPowers: "Causes love, makes women barren" },
  { name: "Botis", rank: "President/Earl", legions: 60, appearance: "Viper, then man with horns/teeth", primaryPowers: "Reveals past/future, reconciles friends/foes" },
  { name: "Bathin", rank: "Duke", legions: 30, appearance: "Strong man with serpent tail on pale horse", primaryPowers: "Knowledge of herbs/stones, instant transport" },
  { name: "Sallos", rank: "Duke", legions: 30, appearance: "Gallant soldier with ducal crown on crocodile", primaryPowers: "Causes love between men/women" },
  { name: "Purson", rank: "King", legions: 22, appearance: "Lion-faced man on bear, with trumpet", primaryPowers: "Reveals hidden things/treasures, past/present/future, divine secrets" },
  { name: "Marax", rank: "Earl/President", legions: 30, appearance: "Bull with human face", primaryPowers: "Teaches astronomy/liberal sciences/herbs" },
  { name: "Ipos", rank: "Prince/Earl", legions: 36, appearance: "Angel/leonine with goose feet, hare tail", primaryPowers: "Wit/courage, reveals future" },
  { name: "Aim", rank: "Duke", legions: 26, appearance: "Man with three heads (serpent, man, calf), fire", primaryPowers: "Sets cities on fire, witty answers" },
  { name: "Naberius", rank: "Marquis", legions: 19, appearance: "Black crane or three-headed dog", primaryPowers: "Teaches arts/rhetoric, restores lost honors" },
  { name: "Glasya-Labolas", rank: "President", legions: 36, appearance: "Dog with griffin wings", primaryPowers: "Invisible, teaches arts, causes bloodshed, reveals future, love/hate" },
  { name: "Bune", rank: "Duke", legions: 30, appearance: "Dragon with three heads", primaryPowers: "Riches, eloquence, wisdom, moves dead" },
  { name: "Ronové", rank: "Marquis/Earl", legions: 20, appearance: "Monster", primaryPowers: "Teaches rhetoric/languages, faithful servants, favor" },
  { name: "Berith", rank: "Duke", legions: 26, appearance: "Red soldier on red horse", primaryPowers: "Turns metals to gold, dignities, true answers (lies if not constrained)" },
  { name: "Astaroth", rank: "Duke", legions: 40, appearance: "Foul angel on infernal dragon, viper in hand", primaryPowers: "Reveals past/present/future, liberal sciences, secrets" },
  { name: "Forneus", rank: "Marquis", legions: 29, appearance: "Sea monster", primaryPowers: "Teaches rhetoric/languages, favor with friends/foes" },
  { name: "Foras", rank: "President", legions: 29, appearance: "Strong man", primaryPowers: "Teaches logic/herbs/stones, invisibility, long life, treasures" },
  { name: "Asmoday", rank: "King", legions: 72, appearance: "Three heads (bull, man, ram), serpent tail, fire", primaryPowers: "Arithmetic/geometry/astronomy, invisibility, treasures" },
  { name: "Gaap", rank: "President/Prince", legions: 66, appearance: "Guide with four kings", primaryPowers: "Philosophy/sciences, love/hate, transport, insensibility" },
  { name: "Furfur", rank: "Earl", legions: 26, appearance: "Hart with fiery tail", primaryPowers: "Storms/lightning, teaches secrets, lies unless constrained" },
  { name: "Marchosias", rank: "Marquis", legions: 30, appearance: "Wolf with griffin wings, serpent tail", primaryPowers: "Strong fighter, true answers" },
  { name: "Stolas", rank: "Prince", legions: 26, appearance: "Raven, then man", primaryPowers: "Teaches astronomy/herbs/stones" },
  { name: "Phenex", rank: "Marquis", legions: 20, appearance: "Phoenix with child's voice", primaryPowers: "Teaches sciences, good poet" },
  { name: "Halphas", rank: "Earl", legions: 26, appearance: "Stock-dove", primaryPowers: "Builds towers, sends warriors" },
  { name: "Malphas", rank: "President", legions: 40, appearance: "Crow, then man", primaryPowers: "Builds houses/towers, reveals enemies' thoughts" },
  { name: "Räum", rank: "Earl", legions: 30, appearance: "Crow, then man", primaryPowers: "Steals treasures, destroys cities, love, past/present/future" },
  { name: "Focalor", rank: "Duke", legions: 30, appearance: "Man with griffin wings", primaryPowers: "Slays/drowns men, controls seas/winds" },
  { name: "Vepar", rank: "Duke", legions: 29, appearance: "Mermaid", primaryPowers: "Guides ships, putrefies wounds, storms" },
  { name: "Sabnock", rank: "Marquis", legions: 50, appearance: "Armed soldier with lion head on pale horse", primaryPowers: "Builds castles, afflicts with wounds/toxins, familiars" },
  { name: "Shax", rank: "Marquis", legions: 30, appearance: "Stock-dove with hoarse voice", primaryPowers: "Steals money/sight/hearing, finds hidden things, familiars" },
  { name: "Viné", rank: "King/Earl", legions: 36, appearance: "Lion on black horse with viper", primaryPowers: "Discovers hidden things/witches, storms, builds/destroys towers" },
  { name: "Bifrons", rank: "Earl", legions: 6, appearance: "Monster, then man", primaryPowers: "Teaches sciences, moves corpses, lights candles on graves" },
  { name: "Vual", rank: "Duke", legions: 37, appearance: "Mighty dromedary, then man", primaryPowers: "Love of women, past/present/future, friendship" },
  { name: "Haagenti", rank: "President", legions: 33, appearance: "Bull with griffin wings, then man", primaryPowers: "Transmutes metals, turns wine to water, wisdom" },
  { name: "Crocell", rank: "Duke", legions: 48, appearance: "Angel", primaryPowers: "Teaches geometry/liberal sciences, warms waters, noises" },
  { name: "Furcas", rank: "Knight", legions: 20, appearance: "Cruel old man with beard, spear", primaryPowers: "Teaches philosophy/astronomy/rhetoric/pyromancy" },
  { name: "Balam", rank: "King", legions: 40, appearance: "Three heads (bull, man, ram), serpent tail", primaryPowers: "Invisibility, wit, true answers about past/present/future" },
  { name: "Alloces", rank: "Duke", legions: 36, appearance: "Soldier on great horse with lion face", primaryPowers: "Teaches astronomy, provides good familiars" },
  { name: "Camio", rank: "President", legions: 30, appearance: "Thrush, then man with sword", primaryPowers: "Understands birds/water/burning, future answers" },
  { name: "Murmur", rank: "Duke/Earl", legions: 30, appearance: "Warrior on griffin with ducal crown", primaryPowers: "Teaches philosophy, constrains souls of deceased" },
  { name: "Orobas", rank: "Prince", legions: 20, appearance: "Horse, then man", primaryPowers: "Past/present/future, dignities, favor of friends/foes, divine secrets" },
  { name: "Gremory", rank: "Duke", legions: 26, appearance: "Beautiful woman with duchess crown on camel", primaryPowers: "Treasures, love of women, past/present/future" },
  { name: "Ose", rank: "President", legions: 30, appearance: "Leopard, then man", primaryPowers: "Madness/delusion, transforms conjurer, true answers" },
  { name: "Amy", rank: "President", legions: 36, appearance: "Flaming fire, then man", primaryPowers: "Astrology/liberal sciences, treasures guarded by spirits" },
  { name: "Oriax", rank: "Marquis", legions: 30, appearance: "Unknown", primaryPowers: "Astrology, planetary changes, transforms men, favor" },
  { name: "Vapula", rank: "Duke", legions: 36, appearance: "Lion with griffin wings", primaryPowers: "Teaches handicrafts/philosophy/sciences" },
  { name: "Zagan", rank: "King/President", legions: 33, appearance: "Bull with griffin wings, then man", primaryPowers: "Transmutes metals/liquids, makes fools wise" },
  { name: "Volac", rank: "President", legions: 38, appearance: "Child with angel wings on dragon", primaryPowers: "Reveals hidden treasures/serpents" },
  { name: "Andras", rank: "Marquis", legions: 30, appearance: "Angel with raven head, owl, sword on wolf", primaryPowers: "Sows discord, slays enemies (dangerous to conjurer)" },
  { name: "Haures", rank: "Duke", legions: 36, appearance: "Leopard, then man with fiery eyes", primaryPowers: "Destroys enemies by fire, past/present/future" },
  { name: "Andrealphus", rank: "Marquis", legions: 30, appearance: "Noisy peacock, then man", primaryPowers: "Geometry/measurements, transforms into birds" },
  { name: "Cimeies", rank: "Marquis", legions: 20, appearance: "Valiant warrior on black horse", primaryPowers: "Grammar/rhetoric/logic, discovers lost things, ruler of Africa" },
  { name: "Amdusias", rank: "Duke", legions: 29, appearance: "Unicorn, then man with trumpet", primaryPowers: "Music, bends trees, good familiars" },
  { name: "Belial", rank: "King", legions: 80, appearance: "Two angels in chariot of fire", primaryPowers: "Distributes dignities/senatorships, favor, good familiars" },
  { name: "Decarabia", rank: "Marquis", legions: 30, appearance: "Star in pentacle, then man", primaryPowers: "Knowledge of birds/herbs/stones, illusion of birds" },
  { name: "Seere", rank: "Prince", legions: 26, appearance: "Beautiful man on winged horse", primaryPowers: "Swift transport, finds treasures, good nature" },
  { name: "Dantalion", rank: "Duke", legions: 36, appearance: "Man with many faces, book in hand", primaryPowers: "Teaches arts/sciences, reads/changes thoughts, love, illusions" },
  { name: "Andromalius", rank: "Earl", legions: 36, appearance: "Man with great serpent", primaryPowers: "Returns stolen goods, punishes thieves, discovers wickedness/secrets" }
];

function generateInvocation(demon) {
  return `I invoke ${demon.name}, ${demon.rank} with ${demon.legions} legions, appearing as ${demon.appearance}, granting ${demon.primaryPowers}.`;
}

function activateAll() {
  goetiaDemons.forEach(demon => {
    console.log(generateInvocation(demon));
  });
}

activateAll();